# -*- coding: utf-8 -*-
"""Shark data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nj7MMTxSPMcT2197e2yg8dm5FJIxQEfA

SHARK TANK INDIA DATA ANALYSIS
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sh=pd.read_csv("/content/shark_tank_analytics_dataset.csv")

sh

sh.info()

sh['Industry'].value_counts()

sh['Industry'].value_counts().plot(kind='bar')

sns.countplot(x=sh['Deal_Status'])

sh['Deal_Status'].value_counts()

sh['Investor'].value_counts().plot(kind='pie',autopct='%.2f')

sh['Investor'].value_counts()

sh.describe()

"""BOXPLOT"""

sns.boxplot(x=sh['Ask_Amount_Lakhs'])

sh['Ask_Amount_Lakhs'].min()

sh['Ask_Amount_Lakhs'].max()

sh['Ask_Amount_Lakhs'].mean()

sh['Ask_Amount_Lakhs'].skew()

"""SCATTERPLOT"""

sns.scatterplot(x=sh['Ask_Amount_Lakhs'],y=sh['Startup_Valuation_Lakhs'])

"""DISTPLOT"""

sns.distplot(sh[sh['Deal_Status']=='Deal']['Startup_Valuation_Lakhs'], hist=True)

"""HEATMAP"""

sns.heatmap(
    pd.crosstab(sh['Industry'], sh['Deal_Status']),
    annot=True,
    fmt='d'
)